### ISSUE TITLE
카테고리로 진입 결과 화면 

### ISSUE THREAD

**Issue by yongbeomkwak** [PrintingAlley/PrintingAlley-iOS#106]
## 🛠 Issue

카테고리 진입 후 결과 화면 구현합니다.

## 📝 To-do

- [x] 데모 앱을 통해 UI 구성
- [x] 네트워크 유즈 케이스 연결
- [x] 필터 화면과 연결 
- [x] 필터 기능 구현
- [x] 카테고리 킹피셔 
- [x] 드래그를 이용한 dimiss
