### ISSUE TITLE
로고 및 3차 디자인 시스템 개편 

### ISSUE THREAD

**Issue by yongbeomkwak** [PrintingAlley/PrintingAlley-iOS#143]
## 🛠 Issue

- 로고 변경
1. 앱 아이콘
2. 네이버 로그인 앱 아이콘
3. 카카오 로그인 앱 아이콘
4. 깃 아이콘 

## 📝 To-do

- [x] 앱 아이콘
- [x] 네이버 로그인 앱 아이콘
- [x] 카카오 로그인 앱 아이콘
- [x] 깃 아이콘 
- [x] 아이콘 이미지 변경
- [x] 색깔 변경 
- [x] 간격 수정
