### ISSUE TITLE
사용할 서드파티 설치

### ISSUE THREAD

**Issue by yongbeomkwak** [PrintingAlley/PrintingAlley-iOS#17]
## 🛠 Issue

사용할 서드파티 라이브러리 설치를 정리한다.

## 📝 To-do

- [ ] 패키지이름 : 클론 주소 / ProductName / 버전
- [ ] Snapkit : https://github.com/SnapKit/SnapKit.git / "SnapKit" / 5.6.0
- [ ] Then : https://github.com/devxoul/Then.git / "Then" / 3.0.0
- [ ] RxMoya : https://github.com/Moya/Moya.git / "RxMoya" / 15.0.3
- [ ] Kingfisher : https://github.com/onevcat/Kingfisher.git / "Kingfisher" / 7.9.1 (RxKingfisher 아님)
