### ISSUE TITLE
검색뷰 QA

### ISSUE THREAD

**Issue by kpk0616** [PrintingAlley/PrintingAlley-iOS#173]
## 📝 To-do

- [x] 인피니티 스크롤
- [x] 검색 아이콘 프레스 시 변경되는 문제 수정
- [x] 검색뷰 X 아이콘 변경 ?
- [x] 검색바 터치 영역 넓히기
