### ISSUE TITLE
Utlity 관련 코드 정리

### ISSUE THREAD

**Issue by yongbeomkwak** [PrintingAlley/PrintingAlley-iOS#18]
## 🛠 Issue

모든 모듈에서 사용할 수 있는 Utlity 내용을 정리합니다.

## 📝 To-do

- [x] DEUBG_LOG: 프린트 대신 사용할 로그
- [x] ColorFromRGB: HexCode를 사용하여 Color로 바꿔줄 코드
- [x] PreferenceManager: 반응형 User 디폴트 매니저 
- [x] wrapNavigationController: 해당 뷰컨을 NavigationController 입힌다.
- [x] APP_WIDTH: 기기 너비 
- [x] APP_HEIGHT : 기기 높이 
- [x] STATUS_BAR_HEGHIT : topSafeArea 높이
- [x] SAFEAREA_BOTTOM_HEIGHT : bottomSafaArea 높이
- [x] APP_VERSION: 앱 버전
- [x] APP_NAME: 앱 이름
- [x] UIView+Extension
  - [x] setRound: 지정하고 싶은 코너를 입력받아 radius 값을 적용시키는 코드
  - [x] addSubviews : 여러 오브젝트를 한꺼번에 addSubview 해주는 코드
- [x] UIFont+Extension
  - [x] 폰트 enum과 사이즈를 받아 적용시키는 코드
  - [x] 폰트 행간, 자간 적용 코드

**Comment by yongbeomkwak** [comment]
유틸리티 3개 명시 완료
