### ISSUE TITLE
저장목록 이름 및 닉네임 관련 이슈

### ISSUE THREAD

**Issue by grace0617** [PrintingAlley/PrintingAlley-iOS#187]
## 🛠 Issue

이름 관련 수정사항 모음 및 토스트 메시지 문구 변경
1) 이미 사용하고 있는 이름으로 설정하려 할 때 토스트 메시지 문구
2) 저장목록 글자수 제한 수정
3) 이름 수정시 디폴트로 기존 이름 작성되어 있기

## 📝 To-do

- [x] <동일이름> 요청이 이미 존재합니다-> (수정) 이미 사용 중인 이름이에요!
- [x] <글자수제한> 저장목록 글자수 제한 10자로 변경
- [ ] <이름변경시> 이름 변경시 기존 이름이 디폴트로 적혀져 있고 거기서 수정하게 해주면 좋겠어요

<img src = "https://github.com/PrintingAlley/PrintingAlley-iOS/assets/128666933/94793f56-0df7-43bd-92a1-3b98bb53221c" width ="250">

![image](https://github.com/PrintingAlley/PrintingAlley-iOS/assets/128666933/5011d7b0-5c36-458a-b0f1-4946b8b23def)
