### ISSUE TITLE
데이터 끊긴 경우 스크롤

### ISSUE THREAD

**Issue by grace0617** [PrintingAlley/PrintingAlley-iOS#193]
## 🛠 Issue

데이터 키고 앱을 집입, 진입하고 데이터 열결해제 하니까 오류메시지가 뜨긴하는데 스크롤 내리니까 반복해서 뜹니다
토스트 메시지도 수정할게요.

## 📝 To-do

- [x] 서버 또는 네트워크에 문제가 생겼어요. 잠시 후 다시 시도해 주세요.
- [x] 경고문구는 한번만 뜰 수 있도록
- [ ] 네트워크 끊기면 저렇게 진입할 수 없도록

https://cdn.discordapp.com/attachments/1175671670837616650/1176402904110878802/RPReplay_Final1700546686.mov?ex=656ebd94&is=655c4894&hm=74ccfe5a1cf4f52ab5d0f0b7364c5af96c2228a587f9ab3d650ee927870a982c&

**Comment by yongbeomkwak** [comment]
@kpk0616  에러 뜨면 , 컬렉션뷰 스크롤 막고, 다시 데이터 재대로 불러오면 , 스크롤 다시 여는거 어때요?
제가 시도한번 해볼께요

**Comment by kpk0616** [comment]
> @kpk0616 에러 뜨면 , 컬렉션뷰 스크롤 막고, 다시 데이터 재대로 불러오면 , 스크롤 다시 여는거 어때요? 제가 시도한번 해볼께요

오 네 카일 고마워요 !!
