### ISSUE TITLE
네이버 로그인 셋팅

### ISSUE THREAD

**Issue by yongbeomkwak** [PrintingAlley/PrintingAlley-iOS#20]
## 🛠 Issue

네이버 로그인 테스트를 위한 간단한 사전 작업

## 📝 To-do

- [x] 네이버 로그인 API 검수를 위한 디자인 제작 요청
- [x]  네이버 키 발급 적용 
- [x] 네이버 로그인 테스트
