### ISSUE TITLE
검색바 키보드 수정 및 텍스트 수정

### ISSUE THREAD

**Issue by grace0617** [PrintingAlley/PrintingAlley-iOS#217]
## 🛠 Issue

검색바키보드 엔터키가 '검색'으로 바껴야 할 거 같아요!
검색바 안에 텍스트 수정을 하겠습니다!

## 📝 To-do

- [x] ~~검색바 돋보기가 검색바를 눌러서 키보드가 떴을 때 엑스나 취소로 바뀌기~~
- [x] 키보드 안에 엔터키가 아니라 검색 버튼이 생기기
- [x] 검색바 안에 텍스트 '인쇄사, 인쇄 방식, 후가공 검색'-> '**인쇄 방식, 후가공, 인쇄사 이름 검색**' 으로 변경
![IMG_90DC7F4FD697-1](https://github.com/PrintingAlley/PrintingAlley-iOS/assets/128666933/5f80ff44-8c3b-4172-aa67-9a7f8954fd4c)
