### ISSUE TITLE
심사 통과 후 할 것

### ISSUE THREAD

**Issue by yongbeomkwak** [PrintingAlley/PrintingAlley-iOS#220]
## 🛠 Issue

1. 1.0.1 버전 통과하면 할 것

## 📸 Image

<img src = "" width ="250">

## 📝 To-do

- [x] 네이버 스킴 제거 
- [x] 강제 업데이트 걸기 
- [x] 피터 네이버 스킴 확인
