### ISSUE TITLE
로그인 화면 스켈레톤

### ISSUE THREAD

**Issue by yongbeomkwak** [PrintingAlley/PrintingAlley-iOS#39]
## 🛠 Issue

- 간단한 로그인 화면

## 📝 To-do

- [ ] 로그인 버튼 색깔 부여
- [x] border
- [x] 유틸리티 코드로 전환
- [x] 로그인 로고 변경
- [x] 폰트 적용
