### ISSUE TITLE
마이 페이지 스켈레톤

### ISSUE THREAD

**Issue by yongbeomkwak** [PrintingAlley/PrintingAlley-iOS#42]
## 📝 To-do

- [x] UserInfo에 name property 추가
- [ ] 로그아웃 기능 구현
- [ ] 1:1 문의하기 메일 시스템
- [x] 마이 페이지 UI 스켈레턴
- [x] 이미지 버튼 구현
