### ISSUE TITLE
네트워크 모듈 테스트

### ISSUE THREAD

**Issue by yongbeomkwak** [PrintingAlley/PrintingAlley-iOS#44]
## 🛠 Issue

구축한 네트워크 모듈 기능을 테스트 합니다.

## 📝 To-do

- [x] GET
- [ ] POST
- [x] 잘못된 처리 픽스 
- [x] Auth 도메인 모듈 생성
- [x] Auth API 스켈레톤 
- [x] XCconfig BASE_URL 수정
