### ISSUE TITLE
픽스할 이슈

### ISSUE THREAD

**Issue by yongbeomkwak** [PrintingAlley/PrintingAlley-iOS#54]
## 🛠 Issue

- 버그 등 간단하게 픽스할 이슈 

## 📝 To-do

- [ ] 다크모드에서도 잘 나오게 흰 배경색 지정하기 (다크모드 고려 x)
- [x] 메일 시스템에 수신자 지정하기
- [ ] 사이닝 다시 시도 ..
