### ISSUE TITLE
모듈 의존성 엉킴 

### ISSUE THREAD

**Issue by yongbeomkwak** [PrintingAlley/PrintingAlley-iOS#59]
## 🛠 Issue

메인 탭바 및 홈 퓨처가 베이스를 의존하지 않아 , 하위 모듈 접근이 불가 했음 (유틸리티, 디자인 시스템)

## 📝 To-do

- [x] 베이스  퓨처 및 인터페이스를 의존 하지 않는 모듈 연결
- [x] 메인 탭바 퓨처 도 하의
- [x] 루트 퓨처에 하위 퓨처들 연결
