### ISSUE TITLE
북마크 도메인 API 연결

### ISSUE THREAD

**Issue by yongbeomkwak** [PrintingAlley/PrintingAlley-iOS#76]
## 🛠 Issue

북마크 도메인 구현

## 📝 To-do

- [x] 도메인 모듈 생성
- [x] API 정의 
- [x] 유즈 케이스 정의
- [x] 데이터 바인딩 및 처리
- [x] 컴포넌트 생성
