### ISSUE TITLE
User 관련 적용

### ISSUE THREAD

**Issue by yongbeomkwak** [PrintingAlley/PrintingAlley-iOS#90]
## 🛠 Issue

- User 관련 작업을 진행합니다.

## 📝 To-do

- [x] User  API 연결
- [x] User  이름 수정 화면 적용
- [x] User 리프래쉬
- [x] User 도메인 모듈 생성
- [x] 프리퍼런스 매니저와 연결
- [x] #77
